# Generated by Django 4.2.23 on 2025-07-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("employee", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="employee", name="age", field=models.IntegerField(default=18)
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.CharField(default="", max_length=50),
        ),
    ]
