# Generated by Django 4.2.23 on 2025-07-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("employee", "0002_employee_age_employee_department")]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(model_name="employee", name="department"),
    ]
