# Generated by Django 4.2.23 on 2025-07-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("employee", "0004_employee_department")]

    operations = [migrations.RemoveField(model_name="employee", name="department")]
