# Generated by Django 4.2.23 on 2025-07-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("employee", "0005_remove_employee_department")]

    operations = [
        migrations.DeleteModel(name="Department"),
        migrations.RemoveField(model_name="employee", name="email"),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
