# Generated by Django 4.2.23 on 2025-07-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0006_delete_department_remove_employee_email_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
